# Dependencies
markdown:             redcarpet
highlighter:          pygments

exclude:              ["bin/"]
timezone:             "Europe/Amsterdam"

# Permalinks
permalink:            pretty

# Setup
title:                Rens Admiraal
title_separator:      " * "
tagline:              "East west, CLI best"
description:          ""
url:                  http://www.rensadmiraal.nl/
baseurl:              /

site:
  locale:             "en_US"

repository: "radmiraal/radmiraal.github.io"

sass:
  sass_dir: "_sass"
  style: compressed

paginate:             6
paginate_path:        "/page/:num/"

plugins:
  - jekyll-redirect-from
