# Dependencies
markdown:             redcarpet
highlighter:          rouge

exclude:              ["bin/"]
timezone:             "Europe/Amsterdam"

# Permalinks
permalink:            pretty

# Setup
title:                Rens Admiraal
tagline:              "East west, CLI best"
description:          ""
url:                  http://www.rensadmiraal.nl/
baseurl:              /
locale:               "en_US"
repository:           "radmiraal/radmiraal.github.io"

sass:
  sass_dir:           "assets/css"
  style:              compressed

paginate:             6
paginate_path:        "/page/:num/"

plugins:
  - jekyll-redirect-from
