name: npm build

on:
  workflow_dispatch:
  push:

jobs:
  type-check:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 17
          cache: 'npm'

      - run: npm ci

      - run: npm run build

      - uses: EndBug/add-and-commit@v8
        with:
          add: "-f dist"
          message: "ci: Auto commit npm build result"
          committer_name: GitHub Actions
          committer_email: github@rensadmiraal.nl
          push: true
